FROM apache/superset:latest
USER root

#wget https://mirror.kraski.tv/soft/google_chrome/linux/102.0.5005.115/google-chrome-stable_102.0.5005.115-1_amd64.deb
#wget https://mirror.cs.uchicago.edu/google-chrome/pool/main/g/google-chrome-stable/google-chrome-stable_102.0.5005.115-1_amd64.deb

RUN apt-get update -y
RUN apt-get install -y wget zip unzip tar nano telnet
RUN wget https://mirror.kraski.tv/soft/google_chrome/linux/102.0.5005.115/google-chrome-stable_102.0.5005.115-1_amd64.deb
RUN apt-get install -y --fix-missing ./google-chrome-stable_102.0.5005.115-1_amd64.deb
RUN rm -f google-chrome-stable_102.0.5005.115-1_amd64.deb
RUN wget https://chromedriver.storage.googleapis.com/102.0.5005.61/chromedriver_linux64.zip
RUN unzip chromedriver_linux64.zip -d /usr/bin
RUN chmod 755 /usr/bin/chromedriver
RUN rm -f chromedriver_linux64.zip
RUN pip install --upgrade pip
RUN pip install --no-cache gevent psycopg2 redis clickhouse-connect clickhouse-driver clickhouse-sqlalchemy celery gunicorn flower prophet holidays==0.23
RUN pip install --no-cache -r superset/translations/requirements.txt
USER superset